### ISSUE TITLE
Bad interaction of function literals with thread-first macros

### ISSUE THREAD

**Issue by silverguo** [cespare/goclj#67]
Hi,

I met a strange indent issue with `goclj`.

Here is a toy example,

With `goclj`,
```clojure
(map #(-> %
          (assoc
            :a 1
              :b 2
              :c 2))
     [{}])
```

With [Calva clj formatter](https://github.com/BetterThanTomorrow/calva-fmt),
```clojure
(map #(-> %
          (assoc
           :a 1
           :b 2
           :c 2))
     [{}])
```

Also for `construct`

With `goclj`,
```clojure
(construct hello
  :a a
  :b b)
```

With [Calva clj formatter](https://github.com/BetterThanTomorrow/calva-fmt),
```clojure
(construct hello
           :a a
           :b b)
```

I personally think the indent of `Calva` is a bit more readable, WDYT?

**Comment by cespare** [comment]
Thanks for the report. There's certainly a problem in the first example; it has something to do with the interaction of an anonymous function and a thread-first macro. Smaller repro:

```
#(-> %
     (assoc
       :a 1
         :b 2))
```

The rest of it all seems to be working as intended. cljfmt makes a host of formatting decisions based on various style guides as well as Liftoff conventions. In your second example, `construct` is explicitly listed in our cljfmt.clj config file to use the `cond1` indent style: for functions and macros that we use frequently such as `construct`, we have intentionally chosen to use a two-space indentation rather than lining up the arguments.
