### ISSUE TITLE
Use lists instead of vectors for namespace `:import`s

### ISSUE THREAD

**Issue by jwhitbeck** [cespare/goclj#68]
Following the recommendations in [How to ns](https://stuartsierra.com/2016/clojure-how-to-ns.html), use vectors instead of lists for the `:import` forms to make the `ns` form easier to read by listing each imported Java class on its own line.

Cjfmt with vectors:

```clojure
(ns liftoff.clj
  "Helper functions for analyzing Clojure code. Intended for local developer tools
  and not for deployed jobs and services."
  (:require [clojure.java.io :as io]
            [clojure.tools.reader :as reader])
  (:import [clojure.lang LineNumberingPushbackReader
            RT]
           [java.io File
            InputStream
            Reader
            StringReader]))
```

Cljfmt with lists

```clojure
(ns liftoff.clj
  "Helper functions for analyzing Clojure code. Intended for local developer tools
  and not for deployed jobs and services."
  (:require [clojure.java.io :as io]
            [clojure.tools.reader :as reader])
  (:import (clojure.lang LineNumberingPushbackReader
                         RT)
           (java.io File
                    InputStream
                    Reader
                    StringReader)))

**Comment by cespare** [comment]
There are many other recommendations on that page, too. cljfmt already does most of the sorting that "How to ns" talks about, but here are other things which it does not do:

- Use the order `:refer-clojure`, then `:require`, then `:import`
- Merge duplicate clauses
- Use the keywords for these rather than symbols (`:require`, not `require`)
- Use lists for these clauses
- Use vectors inside `:require` clauses
- Use lists inside `:import` clauses (what this issue is about)
- Put every `:require`d namespace in a vector, even if there is no  `:as` or `:refer`
- Put `:refer`d or `:exclude`d symbols in a vector
- Start the contents of `:require` or `:import` on a new line after the keyword

Should we do all of these?

**Comment by jwhitbeck** [comment]
The lists inside `:import` clauses seems like the highest value, but the more the better (assuming that's not too much work).

**Comment by cespare** [comment]
At a glance I think they're all easy.

To call it out, I think all of these are more or less what we've been doing at Liftoff except for

> * Start the contents of `:require` or `:import` on a new line after the keyword

Applying that change will touch all our code. (Though the `:import` change already means we're touching ~half the files, so maybe the marginal impact is minor?)
