### ISSUE TITLE
Ignore git directory when walking directory tree

### ISSUE THREAD

**Issue by vishsingh** [cespare/goclj#75]
Today I accidentally ran `cljfmt -w .` in the root of my repository. This touched a file within my `.git` directory that happened to end in `.clj` (because it was the git reflog for a branch whose name ends in `.clj`).

It probably didn't modify that file but I know it did touch the file as its inode modification time was updated.

I propose that `cljfmt` not descend into `.git` directories.

**Comment by cespare** [comment]
If we make a change here, I'd like to do something more principled than teach cljfmt about git.

Cljfmt mostly copies gofmt's behavior, including in this case: it ignores files beginning with `.`, but descends into all directories. This doesn't seem to have been a big issue for gofmt -- I wasn't aware of running gofmt inside .git as a problem people encounter, and the only issue I can find for it was filed back in 2013 (golang/go#5488).

I think this hasn't been a big deal because people rarely run gofmt/cljfmt directly; they usually use editor integrations and rely on scripts/CI/git hooks. Can you comment more on the circumstances where this happened? Is invoking cljfmt on directories manually part of your normal workflow?

If it was a one-time thing, maybe we should just do nothing and see if it continues to be an issue for people.

**Comment by vishsingh** [comment]
It was a one-time thing. I was doing a mass rename across all Clojure files. Hence I also needed to reformat all Clojure files. Once I realized my error, I used the command `cljfmt -w ./*` instead.

**Comment by vishsingh** [comment]
Reading through the comments on the gofmt issue, I think doing nothing sounds like a good path forward for now. If I really want to change cljfmt I can fork the codebase for myself.
